# Generated by Django 3.2.6 on 2021-09-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile',
            field=models.ImageField(default='images/ava.jpg', upload_to='images/'),
        ),
    ]
