# Generated by Django 3.2.3 on 2021-06-21 03:19

from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
