# Generated by Django 3.2.3 on 2021-06-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewer',
            field=models.IntegerField(default=0),
        ),
    ]
